[package]
name = "repomemo-desktop"
version = "0.1.0"
description = "RepoMemo desktop app"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "repomemo_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
repomemo-api.workspace = true
repomemo-domain.workspace = true
serde.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tokio.workspace = true

[build-dependencies]
tauri-build.workspace = true
